sudo: required
dist: trusty
language: python
branches:
  only:
  - master
python:
  - '3.4'
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.13.2/pandoc-1.13.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.13.2-1-amd64.deb
  - sudo apt-get install -y enchant
install:
  - pip install tox
script:
  - tox
after_success:
  - ./tools/deploy.sh
